import { StyleSheet } from "react-native";

const historyStyle=StyleSheet.create({
    maincontainer:{
        flex:1,
        justifyContent:"start",
        alignItems:"center"
    },
    topcontainer:{
        backgroundColor:"#017906",
        height:165,
        width:"100%",

        
    },
    topsubcontainer:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"starts",
        alignItems:"center",
        margin:20
    },
    backbutton:{
        height:36,
        width:36,
        backgroundColor:"#017906",
        justifyContent:"center",
        alignItems:"center",
        display:"flex",
        elevation: 30,
        borderRadius:1000,
        shadowColor:"black",

    },
    toptext:{
        fontSize:15,
        color:"white",
        fontWeight:"800",
        marginLeft:20
    },
    statuscontainer:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width:"100%",
        marginTop:40
    },
    status:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        width:150
    },
    statustext:{
        color:"white",
        fontSize:15,
        fontWeight:"800"
    },
    statusfalsetext:{
        color:"grey",
        fontSize:15,
        fontWeight:"800",
    },
    tufmaincontainer:{
        display:"flex",
        justifyContent:"center",
        alignItems:'center'
    },
    turfcontainer:{
        height:140,
        width:322,
        backgroundColor:"black",
        marginTop:20,
        borderRadius:10,
        display:"flex",
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center"
    },
    turfsubcontainer:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"center",
        alignItems:'center'
    },
    turfimage:{
        height:123,
        width:123,
    },
    turftextcontainer:{
        display:"flex",
        justifyContent:"flex-start",
        alignItems:"center"
    },
    turfheading:{
        color:"white",
        fontSize:17,
        fontWeight:"700",
        marginLeft:20
    },
    turftext:{
        fontSize:10,
        color:"white",
        fontWeight:"700"

    },
    cancelbutton:{
        height:19,
        width:59,
        borderColor:"white",
        borderWidth:1,
        marginTop:20,
        borderRadius:5
    },
    canceltext:{
        fontSize:10,
        fontWeight:"600",
        color:"white",
        textAlign:"center",
        verticalAlign:"middle"
    }
})

export default historyStyle