import { StyleSheet,Dimensions } from "react-native";

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const homeStyle=StyleSheet.create({
    bottomcontainer:{
        
        position:"absolute",
        bottom:0,
        width:"100%",
        height:60,
        backgroundColor:"#393F53"
    },
    bottomsubcontainer:{
        width:"100%",
        height:"100%",
        display:"flex",
        borderStyle:"solid",
        borderWidth:1,
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-evenly",
        alignItems:"center"        
    },
    image:{
        height:30,
        width:30
    },
    maincontainer:{
        height:windowHeight,
        width:windowWidth,
        backgroundColor:"white",
        display:"flex",
        alignItems:"center",
        justifyContent:"flex-start"
    },
    accountcontainer:{
        width:windowWidth,
        height:184,
        backgroundColor:"#017906",
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
        display:"flex",
        alignItems:"flex-start",
        justifyContent:"center"
    },
    userbannercontainer:{
        display:"flex",
        marginLeft:5,
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center"
    },
    userbannertext:{
        color:"white",
        fontWeight:"500"
    },
    searchcontainer:{
        width:windowWidth,
        display:"flex",
        justifyContent:"center",
        alignItems:"center"
    },
    textinput:{
        backgroundColor:"#D9D9D9",
        width:294,
        height:42,
        borderRadius:10,
        marginTop:25
    },
    bannercontainer:{
        width:windowWidth,
        display:"flex",
        justifyContent:"center",
        alignItems:"center"

    },
    bannerimage:{
        margin:5
    },
    optionscontainer:{
        display:"flex",
        width:windowWidth,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-evenly",
        marginTop:10
    },
    options:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        borderRadius:1000,
        
    },
    optionsimage:{
        height:20,
        width:20
    },
    optionstext:{
        fontSize:13,
        fontWeight:"500"
    },
    turfmaincontainer:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        width:windowWidth
    },
    turfcontainer:{
        borderColor:"grey",
        height:120,
        width:340,
        borderWidth:1,
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-evenly",
        alignItems:"center"
    },
    turfimage:{
        height:107,
        width:154
    },
    turftextcontainer:{
        display:"flex",
        justifyContent:"center",
        alignItems:"center"
    },
    turfheading:{
        fontSize:14,
        fontWeight:"700"
    },
    turfcontainerbanner:{
        display:"flex",
        width:340,
        justifyContent:"space-between",
        flexDirection:"row",
        margin:5
    },
    bannertext:{
        fontWeight:"700",
        fontSize:10
    },
    turflocationcontainer:{
        display:"flex",
        flexDirection:"row",
        justifyContent:"center",
        alignItems:"center",
    },
    turftext:{
        color:"#8B8888",
        fontSize:12,
        margin:5
    },
    bookbutton:{
        backgroundColor:"#017906",
        height:19,
        width:62,
        borderRadius:5,
        display:"flex",
        justifyContent:"center",
        alignItems:"center"
    },
    booktext:{
        fontSize:10,
        color:"white",
        fontWeight:"700"
    }


})
export default homeStyle